# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coffee_shop.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coffee_shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63offee_shop.proto\"2\n\rCoffeeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x63offee_type\x18\x02 \x01(\t\"0\n\x0e\x43offeeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"\x1e\n\x0c\x43offeeStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x0cOrderSummary\x12\x14\n\x0ctotal_orders\x18\x01 \x01(\x05\x12\x13\n\x0btotal_price\x18\x02 \x01(\x01\x32\xd3\x01\n\x11\x43offeeShopService\x12.\n\x0bOrderCoffee\x12\x0e.CoffeeRequest\x1a\x0f.CoffeeResponse\x12-\n\nTrackOrder\x12\x0e.CoffeeRequest\x1a\r.CoffeeStatus0\x01\x12,\n\tBulkOrder\x12\x0e.CoffeeRequest\x1a\r.OrderSummary(\x01\x12\x31\n\nCoffeeChat\x12\x0e.CoffeeRequest\x1a\x0f.CoffeeResponse(\x01\x30\x01\x42)\n\x16org.example.coffeeshopB\x0f\x43offeeShopProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coffee_shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.example.coffeeshopB\017CoffeeShopProto'
  _globals['_COFFEEREQUEST']._serialized_start=21
  _globals['_COFFEEREQUEST']._serialized_end=71
  _globals['_COFFEERESPONSE']._serialized_start=73
  _globals['_COFFEERESPONSE']._serialized_end=121
  _globals['_COFFEESTATUS']._serialized_start=123
  _globals['_COFFEESTATUS']._serialized_end=153
  _globals['_ORDERSUMMARY']._serialized_start=155
  _globals['_ORDERSUMMARY']._serialized_end=212
  _globals['_COFFEESHOPSERVICE']._serialized_start=215
  _globals['_COFFEESHOPSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
